version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    command: npx nx serve frontend --configuration=development

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npx nx serve backend --configuration=development
